### ISSUE TITLE
Unknown keystone list Residential 

### ISSUE THREAD

**Issue by nyousefzai** [briviere/keystone-realestate-template#1]
hi , i have reconfigured everything . i am comfortable with librets 

This is the error i am getting now  i was wondering if you can help . 

Thanks in advance   

ReferenceError: Unknown keystone list "Residential"
    at list (/home/nav/Desktop/zoopify-test/mystaff/node_modules/keystone/lib/core/list.js:7:21)
    at Object.<anonymous> (/home/nav/Desktop/zoopify-test/mystaff/extractsResidential.js:5:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

**Comment by briviere** [comment]
It has been some time since I looked at this code.  Do you have Residential.js define under the ./models directory?

**Comment by nyousefzai** [comment]
thanks i figured out , it was keytone issue .
